services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: students_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  api:
    build:
      context: ./api
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/students_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "80:80"
volumes:
  pgdata:
    external: true